version: 2.1
commands:
  save-cache:
    steps:
      - save_cache:
          paths:
            - ./devops
          key: project-4-${CIRCLE_WORKFLOW_ID:0:7}

  restore-cache:
    steps:
      - restore_cache:
          keys: project-4-${CIRCLE_WORKFLOW_ID:0:7}

jobs:
  build-and-lint:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/udacity_devops
    steps:
      - checkout
      - restore-cache
      - run:
          name: Install Project Dependencies
          command: |
            python3 -m venv devops
            . devops/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - save-cache
      - run:
          name: Run Lint
          command: |
            . devops/bin/activate
            make lint

workflows:
  defaults:
    jobs:
      - build-and-lint
      
